### PR TITLE
Test/commitment routes

### PR DESCRIPTION
**Pull request by seyuf**
Minor fix on commitment routes
Set up tests for commitment routes

### CODE REVIEW

**Review by binarious — CHANGES_REQUESTED** [review]
Thank you, @seyuf. Looks good, but could you please change tabs to spaces for indentation? I'm surprised that our current eslint rules don't cover that.

**Comment by seyuf** [comment]
@binarious sorry i was at the center with Banthe, i just came back home 😄 . I will handle this next week. But i though i respected the eslint rules anyway will do, ciao.

**Comment by seyuf** [comment]
@binarious could you recheck your request please?
I believe it has already been handled by the latest commit in the PR. Im respecting your current eslint indent rule witch is 2 spaces. Unless you want to change that i think the PR is fine.

**Comment by binarious** [comment]
@seyuf No worries 🙂 . You've used two tabs instead of spaces:
test_commitment_routes_by_seyuf_ _pull_request__126_ _sirimangalo_meditation-plus-server
Eslint doesn't seem to recognize this. I see this in my editor, too:
1__vim___users_martin_projects_meditation-plus-server__vim_

**Comment by binarious** [comment]
I've added eslint's [no-tabs](http://eslint.org/docs/rules/no-tabs) rule. Now the linting should work as expected.

**Comment by seyuf** [comment]
@binarious indeed my bad :smile: my editor doesn't seem to have problems with it lol. May be because it's a comment i will fix that asap. Thanks

**Review by binarious — APPROVED** [review]

**Comment by binarious** [comment]
That looks good. Thank you @seyuf!

**Pull request merged**
