### PR TITLE
profile routes tests

### PR DESCRIPTION
**Pull request by seyuf**
weird semantic with local field on PUTs to be checked out

### CODE REVIEW

**Comment by seyuf** [comment]
@binarious there seems to be a weird node security could you take a look?  Otherwise I will check it myself when i will have the time :) :peace_symbol: :pray:

**Comment by binarious** [comment]
It is fixed in master. I think you can just rebase/merge master into this
branch :)

Coulibaly <notifications@github.com> schrieb am Di., 28. März 2017, 19:51:

**Comment by seyuf** [comment]
@binarious idts so i was already up to date with the master when i started the PR...

**Comment by binarious** [comment]
Sorry, my bad. It's not in master, yet. @olastor has to approve https://github.com/Sirimangalo/meditation-plus-server/pull/129 first.

**Comment by binarious** [comment]
As a workaround you can also add the `.nsprc` file: https://github.com/Sirimangalo/meditation-plus-server/pull/129/files#diff-03cb303c8d3085901cf5a9214888ad1d

**Review by binarious — APPROVED** [review]

**Comment by binarious** [comment]
Node Security seems stuck. I'll merge nevertheless.

**Pull request merged**
