### PR TITLE
feat: adds "like all"

### PR DESCRIPTION
**Pull request by binarious**
This change is [Reviewable](https://reviewable.io/reviews/sirimangalo/meditation-plus-server/33)

### CODE REVIEW

**Comment by olastor** [comment]
If we get rid of individual likes, storing each user's id who gave a like to each individual meditation session in the db seems to be quite a lot of data not being used (I think). Should we think about refactoring it and replacing the `likes` property of a meditation entry by simply the number of likes and storing the most recent meditation id at the time the user hit the 'like all' button in the 'user' model to differentiate what sessions has already been liked by that user?

**Comment by yuttadhammo** [comment]
That sounds reasonable

**Comment by binarious** [comment]
Great idea, @olastor.

**Comment by binarious** [comment]
@olastor Done. Can be reviewed.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/sirimangalo/meditation-plus-server/33#-:-KQWtu28TvpnQiRaiqj7:b-gg2y7j)_

**Pull request merged**
