### PR TITLE
fix(profile): don't add data from last year to statistics

### PR DESCRIPTION
**Pull request by olastor**
Fixes https://github.com/Sirimangalo/meditation-plus-angular/issues/524

### CODE REVIEW

**Comment by binarious** [comment]
Can you fix the tests, please?

**Comment by olastor** [comment]
@binarious Sorry, didn't noticed the tests were failing. Should be fixed now.

**Review by binarious — APPROVED** [review]

**Comment by ghost** [comment]
Sorry to bother you. Is this fix already live? Cause the statistic is still not correct. Just wondering. :)

**Comment by binarious** [comment]
Not yet, sorry. We will release a new version with a lot of changes in the next weeks, I guess.

**Pull request merged**
